### ISSUE TITLE
Missing the metakgp banner

### ISSUE THREAD

**Issue by grapheo12** [metakgp/what-slot#2]
There is no footer on the project that shows the usual MetaKGP banner: 'Maintained by MetaKGP with ♥'.

**Comment by aditimaurya** [comment]
Hey @grapheo12, can I take this issue?

**Comment by aditimaurya** [comment]
@grapheo12  can you please give me some more details, so that I can start my work?

**Comment by aditimaurya** [comment]
@thealphadollar can you please give me a little more details about the position and other minor things so that I can start?

**Comment by grapheo12** [comment]
Hey @aditimaurya , thanks for looking into the issue. Sorry I approached late.

You can check out the footer of sarathi.metakgp.org for the banner. Generally, we put the metakgp banner at the footer of all our apps.

I am talking about something like this: 
![image](https://user-images.githubusercontent.com/16435932/93178910-91940f80-f752-11ea-9b6c-d9f5efdea9df.png)

**Comment by aditimaurya** [comment]
> I am talking about something like this:
> ![image](https://user-images.githubusercontent.com/16435932/93178910-91940f80-f752-11ea-9b6c-d9f5efdea9df.png)

thanks a lot for the information.

**Comment by aditimaurya** [comment]
@grapheo12  I was trying to add the banner, so there are two problems which I'm facing, please help me with that.
1. When I'm trying to put the link of metakgp it's not working while the Github link is working. 
2. I am doing all the changes here: template --> home.HTML, while I'm running this file individually(on the notepad or other editors), I'm getting the footer element. But when I'm merging this to my forked repo and then running it, it's not working. So can you please tell me am I missing something here?

**Comment by thealphadollar** [comment]
Hey Aditi, please create a pull request with your code adding [WIP] in
title. Thereafter, we can discuss the issues and potential solutions there.

cc/ @grapheo12

**Comment by grapheo12** [comment]
Hey @aditimaurya , did you forget to add `https://` before the link?
